enum MessageType {
    L1CRTNDESTROYED = "L1CRTNDESTROYED",
    L1BATTLEUIPORTTAP = "L1BATTLEUIPORTTAP",
    L1BATTLECHARTAP = "L1BATTLECHARTAP",
    L1BATTLECHARPORTTAP = "L1BATTLECHARPORTTAP",
    L1TOUCHLABELTAP = "L1TOUCHLABELTAP",
    L2CELLTAP = "L2CELLTAP",
    L2CHARTAP = "L2CHARTAP",
    L2TIMEPORTTAP = "L2TIMEPORTTAP",
    L2USEENERGY = "L2USEFIRE",
    L2ADDENERGY = "L2ADDFIRE"
}
